DROP SCHEMA IF EXISTS VinhoX;
CREATE SCHEMA VinhoX;
USE VinhoX;

CREATE TABLE USERS(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NULL,
    TELEFONE VARCHAR(14) NULL
);

CREATE TABLE ENDERECO(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	CIDADE VARCHAR(50) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    LOGRADOURO VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    NUMERO VARCHAR(50) NOT NULL,
    COMPLEMENTO VARCHAR(50) NULL,
    CEP CHAR(8) NOT NULL,
    IDUSER INT UNSIGNED NOT NULL
);

CREATE TABLE PRODUTO(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    PRECOUNITARIO FLOAT (6,2) UNSIGNED NOT NULL,
    VALORMEDIDA FLOAT (6,2) UNSIGNED NOT NULL,
    IDUNMEDIDA INT UNSIGNED NOT NULL
    );

CREATE TABLE UNMEDIDA(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE METODOPAGAMENTO(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE COMPRA(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    VALORFINAL FLOAT (6,2) NOT NULL,
    IDUSER INT UNSIGNED NOT NULL,
    IDSTATUSCOMPRA INT UNSIGNED NOT NULL,
    IDMETODOPAGAMENTO INT UNSIGNED
);

CREATE TABLE STATUSCOMPRA(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE ITEMCOMPRA(
	ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	QUANTIDADE INT UNSIGNED NOT NULL,
    VALORTOTAL FLOAT (6,2) NOT NULL,
    IDPRODUTO INT UNSIGNED NOT NULL,
    IDCOMPRA INT UNSIGNED
);

ALTER TABLE ENDERECO ADD FOREIGN KEY (IDUSER) REFERENCES USERS (ID);
ALTER TABLE PRODUTO ADD FOREIGN KEY (IDUNMEDIDA) REFERENCES UNMEDIDA (ID);
ALTER TABLE COMPRA ADD FOREIGN KEY (IDUSER) REFERENCES USERS (ID);
ALTER TABLE COMPRA ADD FOREIGN KEY (IDSTATUSCOMPRA) REFERENCES STATUSCOMPRA (ID);
ALTER TABLE COMPRA ADD FOREIGN KEY (IDMETODOPAGAMENTO) REFERENCES METODOPAGAMENTO (ID);
ALTER TABLE ITEMCOMPRA ADD FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (ID);
ALTER TABLE ITEMCOMPRA ADD FOREIGN KEY (IDCOMPRA) REFERENCES COMPRA (ID);

INSERT INTO USERS (LOGIN, SENHA, NOME, EMAIL, TELEFONE) VALUES 
				  ('admin','admin', 'admin', 'admin@admin.com','123456789'),
				  ('igor','123', 'Igor Bittencourt', 'igorzaum@gmail.com', '987654321');
                  
INSERT INTO ENDERECO (CIDADE, BAIRRO, LOGRADOURO, ESTADO, NUMERO, CEP, IDUSER) VALUES 
					 ('Blumenau','Garcia', 'Rua Amazonas', 'Santa Catarina', '3000', '89022002', '1'),
					 ('Pomerode','Testo Central', 'Rua Quinze de Novembro', 'Santa Catarina', '821', '89107000', '2');
 
INSERT INTO UNMEDIDA (NOME, DESCRICAO) VALUES 
					 ('un','item por unidade'),
					 ('ml','item por mililítro'),
					 ('l','item por lítro');

INSERT INTO PRODUTO (NOME, DESCRICAO, PRECOUNITARIO, VALORMEDIDA, IDUNMEDIDA) VALUES 
					('Vinho Tinto Suave São José','Vinho de mesa tinto tipo suave da marca São José', '8.75', '600', '2'),
					('Rolha especial','Rolha a vulsa especial para lacre de garrafas em geral', '5', '1', '1');
                     
INSERT INTO METODOPAGAMENTO (NOME) VALUES 
							('Crédito'),
							('Débito'),
							('Pix');
                            
INSERT INTO STATUSCOMPRA (NOME) VALUES 
					     ('Indisponível'),
					     ('Em processamento'),
                         ('Concluído'),
                         ('Erro no pagamento'),
						 ('Aguardadno pagamento');
                         
INSERT INTO COMPRA (VALORFINAL, IDUSER, IDSTATUSCOMPRA, IDMETODOPAGAMENTO) VALUES 
				   ('32.5', '1', '5', '3'),
				   ('28.75','2', '3', '2');

INSERT INTO ITEMCOMPRA (QUANTIDADE, VALORTOTAL, IDPRODUTO, IDCOMPRA) VALUES 
					   ('2','17.5', '1', '1'),
					   ('3','15', '2', '1'),
                       ('1','8.75', '1', '2'),
					   ('4','20', '2', '2');

